[package]
name = "todo_api"
version = "0.1.0"
edition = "2024"
rust-version = "1.97"

[dependencies]
anyhow = { workspace = true }
axum = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
tokio = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
http-body-util = { workspace = true }

[dev-dependencies]
tower = { workspace = true, features = ["util"] }
